### 1 dimension array    ALSO CALLED VECTOR

In [1]:


import numpy as np

a=np.array([5,5,5,])

a


array([5, 5, 5])

In [2]:
type(a)

numpy.ndarray

### 2 dimension array   ALSO CALLED MATRIX

In [3]:
import numpy as np
b=np.array([[5,5,5],[5,5,5],[5,5,5]])
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [4]:
len(a)

3

In [5]:
a[0]

5

In [6]:
b[0]

array([5, 5, 5])

In [7]:
b[0:]

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

### 1D array Functions

In [8]:
c=np.zeros(1)
c

array([0.])

In [9]:
d=np.ones(1)
d

array([1.])

In [10]:
e=np.empty(3)
e

array([0., 0., 0.])

In [11]:
# with range of elements
f=np.arange(5)
f

array([0, 1, 2, 3, 4])

In [12]:
# with specific range of elements
g=np.arange(2,20)
g

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [13]:
# continue
h=np.arange(2,20,2)
h

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
#linearly space array
i=np.linspace(0,10,num=5)
i

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [15]:
j=np.ones(5,dtype=np.int8)
j

array([1, 1, 1, 1, 1], dtype=int8)

In [16]:
k=np.ones(5,dtype=np.float64)
k

array([1., 1., 1., 1., 1.])

### 2D array functions

In [17]:
l=np.zeros((2,2))
l

array([[0., 0.],
       [0., 0.]])

In [18]:
m=np.ones((2,2))
m

array([[1., 1.],
       [1., 1.]])

In [19]:
n=np.empty((3,4))
n

array([[1.28594178e-311, 2.81617418e-322, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 1.58817677e-052, 5.44623678e-090,
        1.20009354e-071],
       [9.98571634e-048, 5.49491238e+170, 6.48224659e+170,
        4.93432906e+257]])