### Numpy for 1D array

In [1]:
import numpy as np

food=np.array(["Samosa","Pakora","Raita"])
food

array(['Samosa', 'Pakora', 'Raita'], dtype='<U6')

In [2]:
price=np.array([5,5,5])
price

array([5, 5, 5])

In [3]:
type(price)

numpy.ndarray

In [4]:
len(price)

3

In [5]:
price[1]   #index 1

5

In [6]:
price[0:3]

array([5, 5, 5])

In [7]:
a=np.zeros((2))
a

array([0., 0.])

In [8]:
b=np.ones((2))
b

array([1., 1.])

In [9]:
c=np.empty((3))
c

array([0., 0., 0.])

In [10]:
# specify
d=np.arange(5)
d

array([0, 1, 2, 3, 4])

In [11]:
# specific interval
e=np.arange(0,11)
e

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
# table of 5
f=np.arange(0,55,5)
f

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [13]:
# lin space
g=np.linspace(0,10,num=5)   # 5 is numbers of occurance
g

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [14]:
h=np.ones(5,dtype=np.float16)
h

array([1., 1., 1., 1., 1.], dtype=float16)

### Array Functions

In [15]:
a=np.array([2,2.5,3,4,1])
a

array([2. , 2.5, 3. , 4. , 1. ])

In [16]:
a.sort()
a

array([1. , 2. , 2.5, 3. , 4. ])

In [17]:
b=np.array([1,2.2,3,4.4,0])
b

array([1. , 2.2, 3. , 4.4, 0. ])

In [18]:
c=np.concatenate((a,b))
c

array([1. , 2. , 2.5, 3. , 4. , 1. , 2.2, 3. , 4.4, 0. ])

In [19]:
c.sort()
c

array([0. , 1. , 1. , 2. , 2.2, 2.5, 3. , 3. , 4. , 4.4])

### 2D Array    Concatination

In [20]:
a=np.array(([[2,2,2],[2,2,2]]))
a

array([[2, 2, 2],
       [2, 2, 2]])

In [21]:
b=np.array(([[2,2,2],[2,2,2]]))
b

array([[2, 2, 2],
       [2, 2, 2]])

In [22]:
c=np.concatenate(([a],[b]),axis=0)    # First way
c

array([[[2, 2, 2],
        [2, 2, 2]],

       [[2, 2, 2],
        [2, 2, 2]]])

In [23]:
c=np.concatenate((a,b),axis=0)       # Second way
c

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [24]:
a=np.array(([1,2,3],[4,5,6],[7,8,9]))
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
a.ndim

2

### 3D array

In [26]:
b=np.array(([[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]))
b

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

### find no of dimension

In [27]:
b.ndim

3

### size of array

In [28]:
b.size

18

### shape of array

In [29]:
b.shape

(3, 2, 3)

In [30]:
a=np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
b=a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
c=np.reshape(a,newshape=(1,9),order='c')
c

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

### Convert 1D into 2D array

In [33]:
d=a[np.newaxis,:]
d

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [34]:
e=a[:,np.newaxis]
e

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

### slicing of array

In [35]:
a[1:9]


array([1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

### Simple Multiply

In [37]:
a*6

array([ 0,  6, 12, 18, 24, 30, 36, 42, 48])

In [38]:
a.sum()

36

In [39]:
a.mean()

4.0